language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist
  - php -S localhost:8080 ./web/index.php &
  - sleep 3

script:
  - ./bin/behat --config behat.dist.yml --profile travis
